export const members = [
  {
    clerkId: "user_2SqLH",
    firstName: "Samantha",
    lastName: "Altman",
    email: "samantha_altman@gmail.com",
    profilePicture: "",
    online: "GET /session (status: active)",
    id: "zfafafz",
    city: "",
    country: "",
    subscription: "standard | vip | premium",
    role: "user | moderator",
    roomId: "room_2SqLH",
  },
  {
    clerkId: "user_jMwNQ",
    firstName: "Clara",
    lastName: "Hilfilgher",
    email: "clara_hilfilgher@gmail.com",
    profilePicture: "",
    online: "GET /session (status: active)",
    id: "zfafafz",
    age: 34,
    city: "",
    country: "",
    subscription: "standard | vip | premium",
    role: "user | moderator",
    roomId: "room_1EfPc",
  },
  {
    clerkId: "user_Fjtt4",
    firstName: "Baptiste",
    lastName: "Muday",
    email: "baptiste_muday@gmail.com",
    age: 24,
    profilePicture: "",
    online: "GET /session (status: active)",
    id: "zfafafz",
    city: "",
    country: "",
    subscription: "standard | vip | premium",
    role: "user | moderator",
    roomId: "room_2SqLH",
  },
  {
    clerkId: "user_2jMNK",
    firstName: "Nathan",
    lastName: "Toto",
    email: "nathan_toto@gmail.com",
    age: 18,
    profilePicture: "",
    online: "GET /session (status: active)",
    id: "zfafafz",
    city: "",
    country: "",
    subscription: "standard | vip | premium",
    role: "user | moderator",
    roomId: "room_3zEr7",
  },
  {
    clerkId: "user_jMwNQ",
    firstName: "Solène",
    lastName: "MUDAY",
    email: "solene_muday@gmail.com",
    age: 20,
    profilePicture: "",
    online: "GET /session (status: active)",
    id: "zfafafz",
    city: "",
    country: "",
    subscription: "standard | vip | premium",
    role: "user | moderator",
    roomId: "room_3zEr7",
  },
  {
    clerkId: "user_wNQ7d",
    firstName: "Cyrille",
    lastName: "Toto",
    email: "cyrille_toto@gmail.com",
    age: 50,
    profilePicture: "",
    online: "GET /session (status: active)",
    id: "zfafafz",
    city: "",
    country: "",
    subscription: "standard | vip | premium",
    role: "user | moderator",
    roomId: "room_23Frd",
  },
];

export const rooms = [
  {
    id: "room_2SqLH",
    name: "home",
    nbUsers: 103,
    image: "",
  },
  {
    id: "room_23Frd",
    name: "agua",
    nbUsers: 89,
    image: "",
  },
  {
    id: "room_3zEr7",
    name: "dance",
    nbUsers: 173,
    image: "",
  },
  {
    id: "room_2Sdda",
    name: "pop",
    nbUsers: 124,
    image: "",
  },
  {
    id: "room_1EfPc",
    name: "jazz",
    nbUsers: 380,
    image: "",
  },
  {
    id: "room_7AmPn",
    name: "rumba",
    nbUsers: 29,
    image: "",
  },
];

export const articles = [
  {
    id: "article_7AmPn",
    title: "home",
    content: "lorem",
    coverImage: "",
  },
  {
    id: "article_jMwNQ",
    title: "home",
    content: "lorem",
    coverImage: "",
  },
  {
    id: "article_2jMNK",
    title: "home",
    content: "lorem",
    coverImage: "",
  },
  {
    id: "article_wNQ7d",
    title: "home",
    content: "lorem",
    coverImage: "",
  },
  {
    id: "article_1EfPc",
    title: "home",
    content: "lorem",
    coverImage: "",
  },
  {
    id: "article_Fjtt4",
    title: "home",
    content: "lorem",
    coverImage: "",
  },
];

export const privateMessages = [
  {
    id: 1,
    senderId: "user_2SqLH",
    receiverId: "user_wNQ7d",
    text: "hello",
    image: "",
    // createdAt: ,
  },
  {
    id: 2,
    senderId: "user_jMwNQ",
    receiverId: "user_2SqLH",
    text: "hey",
    image: "",
    // createdAt: ,
  },
  {
    id: 3,
    senderId: "user_wNQ7d",
    receiverId: "user_jMwNQ",
    text: "what's up?",
    image: "",
    // createdAt: ,
  },
];

export const roomMessages = [
  {
    id: 1,
    senderId: "user_wNQ7d",
    text: "hello everybody!",
    image: "",
    roomId: "room_2SqLH",
    // createdAt: ,
  },
  {
    id: 1,
    senderId: "user_wNQ7d",
    text: "hello world!",
    image: "",
    roomId: "room_23Frd",
    // createdAt: ,
  },
  {
    id: 1,
    senderId: "user_wNQ7d",
    text: "hello coders!",
    image: "",
    roomId: "room_3zEr7",
    // createdAt: ,
  },
];
